# Dockerfile

FROM redhat/ubi9-init
COPY .config/entitlement/* /etc/pki/entitlement
ADD .config/rhsm.tgz /etc/rhsm
RUN rm /etc/rhsm-host
RUN subscription-manager repos --enable rhel-9-for-x86_64-baseos-rpms
RUN yum update -y
