---
- hosts: localhost
  gather_facts: no
  name: Install Non-RHEL
  tasks:
    - name: EPEL
      ansible.builtin.package:
        name:
          - epel-release
        state: latest
      when: os_name != "rhel"
- hosts: localhost
  gather_facts: no
  name: Install RHEL
  tasks:
    - name: EPEL
      ansible.builtin.package:
        name:
          - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ os_major }}.noarch.rpm"
        state: latest
      when: os_name == "rhel"
- hosts: localhost
  gather_facts: no
  name: Install Main
  tasks:
    - name: Packages
      ansible.builtin.package:
        name:
          - jq
          - wget
          - vim-enhanced
          - java-11-openjdk
          - maven
          - nc
          - yum-utils
          - ca-certificates
          - net-tools
        state: latest
